-- 20 Get ProductID, ProductName, and the total revenue generated by each product
SELECT
    Product.ProductID,
    Product.ProductName,
    SUM(Sales.TotalAmount) AS TotalRevenue
FROM Product
JOIN Sales 
    ON Product.ProductID = Sales.ProductID
GROUP BY Product.ProductID, Product.ProductName
ORDER BY TotalRevenue DESC;
